name: Build Android AAB from ZIP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Unzip project
      run: unzip Mgcsolutes.zip -d project

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission
      run: chmod +x project/gradlew

    - name: Build AAB
      run: ./project/gradlew -p project bundleRelease

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: project/app/build/outputs/bundle/release/app-release.aab
